name: backend-api-stack

services:
  backend-api:
    image: lebondeveloppeur/backend-s8-api:latest
    container_name: backend-api
    environment:
      - MONGO_URI=mongodb://root:pass-123@92.113.149.44:27017/book-store?authSource=admin  # MongoDB connection URI
      - PORT=3001  # Port to run the backend API
    ports:
      - '3001:3001'


    